# pyproject.toml

[project]
name = "starkiller"
version = "0.1.0"
description = "Make fake MUSE cubes."
readme = "README.md"
requires-python = ">=3.6"
license = {file = "LICENSE"}
authors = [
  {email = "ryan.ridden@canterbury.ac.nz"},
  {name = "Ryan Ridden"}
]

maintainers = [
  {name = "Brayden Leicester", email = "brayden.leicester@canterbury.ac.nz"}
]

dependencies = [
    'numpy', 
    'matplotlib',
    'pysynphot',
    'extinction',
    'pandas',
    'scipy',
    'astropy',
    'astroquery',
    'photutils',
    'joblib',
    'scikit-image',
    'multiprocess',
    'opencv-python'
]

[build-system]
# XXX: If your project needs other packages to build properly, add them to this list.
requires = ["setuptools >= 42.0.0"]
build-backend = "setuptools.build_meta"

[project.urls]
repository = "https://github.com/CheerfulUser/starkiller"
